TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.2

  max_vel_theta: 1
  min_vel_theta: -1

  min_in_place_vel_theta: 0.2

  acc_lim_theta: 2.5
  acc_lim_x: 2.5

  xy_goal_tolerance: 0.1

  sim_time: 3
  sim_granularity: 0.02
  vx_samples: 5
  vtheta_samples: 10
  controller_frequency: 20

  occdist_scale: 1 # The weighting for how much the controller should attempt to avoid obstacles
  holonomic_robot: true