obstacle_range: 5
raytrace_range: 5
footprint: [[0.3, 0.15], [0.3, -0.15], [-0.3, -0.15], [-0.3, 0.15]]

inflation_radius: 0.55


#layer definitions
static:
    map_topic: /projected_map
    subscribe_to_updates: true
    track_unknown_space: false

obstacles: 
    observation_sources: point_cloud_sensor
    sensor_frame: &depth_camera "RoboDog/base_link/SensorHolder/Sensors/DepthCamera"
    point_cloud_sensor: {sensor_frame: *depth_camera, data_type: PointCloud2, topic: /realsense/depth/points, marking: true, clearing: true}

inflation:
    inflation_radius: 55
