obstacle_range: 5
raytrace_range: 5
# max_obstacle_height: 0.5
footprint: [[0.3, 0.15], [0.3, -0.15], [-0.3, -0.15], [-0.3, 0.15]]

#layer definitions
static_layer:
    map_topic: /projected_map
    subscribe_to_updates: true
    track_unknown_space: false

obstacles_layer: 
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {sensor_frame: "RoboDog/base_link/SensorHolder/Sensors/DepthCamera", data_type: PointCloud2, topic: /realsense/depth/points, marking: true, clearing: true}

inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 10
