obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.15, 0.3], [0.15, -0.3], [-0.15, -0.3], [-0.15, 0.3]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

sensor_frame: &depth_camera "RoboDog/base_link/SensorHolder/Sensors/DepthCamera"
point_cloud_sensor: {sensor_frame: *depth_camera, data_type: PointCloud, topic: /realsense/depth/points, marking: true, clearing: true}